apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: get-users
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: ${REGISTRY_URL}/get-users:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              cpu: "1"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
