
  import { aliases as _add } from './cmds/add';
import { aliases as _addproject } from './cmds/addproject';
import { aliases as _api } from './cmds/api';
import { aliases as _ast } from './cmds/ast';
import { aliases as _bundle } from './cmds/bundle';
import { aliases as _createdb } from './cmds/createdb';
import { aliases as _deploy } from './cmds/deploy';
import { aliases as _dropdb } from './cmds/dropdb';
import { aliases as _dump } from './cmds/dump';
import { aliases as _explorer } from './cmds/explorer';
import { aliases as _export } from './cmds/export';
import { aliases as _ext } from './cmds/ext';
import { aliases as _extension } from './cmds/extension';
import { aliases as _format } from './cmds/format';
import { aliases as _generate } from './cmds/generate';
import { aliases as _info } from './cmds/info';
import { aliases as _init } from './cmds/init';
import { aliases as _install } from './cmds/install';
import { aliases as _maketest } from './cmds/maketest';
import { aliases as _package } from './cmds/package';
import { aliases as _plan } from './cmds/plan';
import { aliases as _publish } from './cmds/publish';
import { aliases as _rename } from './cmds/rename';
import { aliases as _resolve } from './cmds/resolve';
import { aliases as _revert } from './cmds/revert';
import { aliases as _server } from './cmds/server';
import { aliases as _sqitch } from './cmds/sqitch';
import { aliases as _start } from './cmds/start';
import { aliases as _template } from './cmds/template';
import { aliases as _test } from './cmds/test';
import { aliases as _verify } from './cmds/verify';
import { aliases as _version } from './cmds/version';

  module.exports['add'] = _add;
module.exports['addproject'] = _addproject;
module.exports['api'] = _api;
module.exports['ast'] = _ast;
module.exports['bundle'] = _bundle;
module.exports['createdb'] = _createdb;
module.exports['deploy'] = _deploy;
module.exports['dropdb'] = _dropdb;
module.exports['dump'] = _dump;
module.exports['explorer'] = _explorer;
module.exports['export'] = _export;
module.exports['ext'] = _ext;
module.exports['extension'] = _extension;
module.exports['format'] = _format;
module.exports['generate'] = _generate;
module.exports['info'] = _info;
module.exports['init'] = _init;
module.exports['install'] = _install;
module.exports['maketest'] = _maketest;
module.exports['package'] = _package;
module.exports['plan'] = _plan;
module.exports['publish'] = _publish;
module.exports['rename'] = _rename;
module.exports['resolve'] = _resolve;
module.exports['revert'] = _revert;
module.exports['server'] = _server;
module.exports['sqitch'] = _sqitch;
module.exports['start'] = _start;
module.exports['template'] = _template;
module.exports['test'] = _test;
module.exports['verify'] = _verify;
module.exports['version'] = _version;

  