#!/usr/bin/env bash

if [ -z "$1" ]
  then
    echo "please add a message"
    exit
fi



find . -name yarn.lock | grep -v node_modules | xargs rm
git add .
git commit -am "$1"
lerna publish
sleep 5

version=$(awk '/version/{gsub(/("|",)/,"",$2);print $2};' lerna.json)
echo $version
npm install -g skitch@$version
