name: Build Docker Images

on:
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build node-sqitch image
        working-directory: docker/node-sqitch
        run: make build

      - name: Build pgvector image
        working-directory: docker/pgvector
        run: make build
