name: Build Docker Images

on:
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Build pgvector image
        working-directory: docker/pgvector
        run: docker build -t pyramation/node-pgvector:20.12.0 .
